name: Upload Python Package

on:
    push:
        tags:
            - "v*"

permissions:
    contents: read

jobs:
    windows-build:
        uses: ./.github/workflows/windows-exe.yml

    release-build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - uses: actions/setup-python@v6
              with:
                  python-version: "3.x"

            - name: Build release distributions
              run: |
                  cd xmu-rollcall-cli
                  python -m pip install build
                  python -m build

            - name: Upload distributions
              uses: actions/upload-artifact@v4
              with:
                  name: release-dists
                  path: xmu-rollcall-cli/dist/
                  if-no-files-found: error

    github-release:
        needs: [release-build, windows-build]
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v6

            - name: Download distributions
              uses: actions/download-artifact@v5
              with:
                  name: release-dists
                  path: dist

            - name: Download Windows executable
              uses: actions/download-artifact@v5
              with:
                  name: xmurollcall-cli-windows-x64
                  path: dist

            - name: Create GitHub Release
              env:
                  GH_TOKEN: ${{ github.token }}
                  RELEASE_TAG: ${{ github.ref_name }}
              run: |
                  gh release create "$RELEASE_TAG" \
                  dist/* \
                  --title "$RELEASE_TAG" \
                  --notes "" \
                  --verify-tag
